### PR TITLE
Reviews-slider

### PR DESCRIPTION
**Pull request by Sajaas**
* Added the reviews to a yml-file
* Added Swedish review partial index & student page
* Added english reviews partial to index
screen shot 2018-01-26 at 15 09 04
screen shot 2018-01-26 at 15 14 15

### CODE REVIEW

**Comment by tochman** [comment]
Please make the link `target="_blank", okay? We want the user to stay on our site.

**Comment by Sajaas** [comment]
@tochman I already used `target: :_blank` in the `link_to`, is that not correct? Or am I missing it in some specific place?

**Comment by tochman** [comment]
Please try it here: https://deploy-preview-6--pedantic-engelbart-0030f4.netlify.com/

**Comment by Sajaas** [comment]
@tochman That's really weird. It opens in a new tab, then closes it and moves away from the CA-site. I can't make it stay in a new tab, even with `'target: 'blank'` or `"target: 'blank"`?!

**Comment by tochman** [comment]
It's `target="_blank"` @Sajaas ;-)

**Comment by Sajaas** [comment]
@tochman Yup yup, that's what I've tried. Still the same result.

**Pull request merged**
